### ISSUE TITLE
How to provide DICOM images through SlicerWeb to 3dSlicerDockers/3DSlicer Application

### ISSUE THREAD

**Issue by rawl05** [pieper/SlicerWeb#4]
I've been able to load the SlicerWeb Module into the 3DSlicer. The server is spinning at http://localhost:2016.

But I'm not able to identify how to load DICOM(Metadata) files through the SlicerWeb using URL.

Can we load the DICOM or Non-DICOM images by passing the bucket URLs in JSON format?

**Comment by pieper** [comment]
There's no defined rest endpoint for that, but you can easily trigger any Slicer functionality using the `repl` endpoint.

For example this line in the browser address bar or via curl will print the number 10 to the python console.

`http://localhost:2016/slicer/repl?source=print(10)`

You can combine this with the logic provided by [the DICOMweb infrastructure](https://discourse.slicer.org/t/new-dicomweb-features-launch-slicer-from-web-browser-and-download-upload-data-sets-to-the-cloud-using-dicomweb/17811) to fetch dicom files from a URL.

Obviously you need to be very careful since this endpoint exposes full control of the application (and full access to the host computer) to anyone who can reach it.  It allows arbitrary code execution, which is good for experiments but not safe for production unless it is behind an authenticating proxy or other security boundary.
